#!/usr/bin/env node
/**
 * build.js — Assemble exam platform into single HTML file
 *
 * Reads parsed exam data + templates + vendor libs → single self-contained HTML
 *
 * Usage: node build.js <exam-data.json> [--output path.html] [--title "Exam Title"]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const dataPath = args.find(a => !a.startsWith('--'));
const outputIdx = args.indexOf('--output');
const titleIdx = args.indexOf('--title');

if (!dataPath) {
  console.error('Usage: node build.js <exam-data.json> [--output path.html] [--title "Title"]');
  process.exit(1);
}

const examData = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const meta = examData.meta || {};
const title = (titleIdx >= 0 ? args[titleIdx + 1] : null) || meta.title || '练习平台';

// Paths
const SKILL_DIR = path.resolve(__dirname, '..');
const TPL_DIR = path.join(SKILL_DIR, 'templates');
const VENDOR_DIR = path.join(SKILL_DIR, 'vendor');

// Read templates
const styles = fs.readFileSync(path.join(TPL_DIR, 'styles.css'), 'utf8');
const bodyRaw = fs.readFileSync(path.join(TPL_DIR, 'body.html'), 'utf8');

// Read vendor files
const cmFiles = ['codemirror.min.js', 'python.min.js', 'show-hint.min.js', 'matchbrackets.min.js', 'closebrackets.min.js'];
const cmCSS = ['codemirror.min.css', 'show-hint.min.css'];

const cmJS = cmFiles.map(f => {
  const p = path.join(VENDOR_DIR, f);
  if (!fs.existsSync(p)) { console.error(`Missing vendor: ${f}`); process.exit(1); }
  return fs.readFileSync(p, 'utf8');
}).join('\n');

const cmCSSText = cmCSS.map(f => {
  const p = path.join(VENDOR_DIR, f);
  if (!fs.existsSync(p)) { console.error(`Missing vendor CSS: ${f}`); process.exit(1); }
  return fs.readFileSync(p, 'utf8');
}).join('\n');

const confettiJS = fs.readFileSync(path.join(VENDOR_DIR, 'canvas-confetti.browser.js'), 'utf8');
const skulptJS = fs.readFileSync(path.join(VENDOR_DIR, 'skulpt.min.js'), 'utf8');
const skulptStdlibJS = fs.readFileSync(path.join(VENDOR_DIR, 'skulpt-stdlib.js'), 'utf8');

// Generate body HTML with dynamic counts
const body = bodyRaw
  .replace(/{{TITLE}}/g, title)
  .replace(/{{CHOICE_COUNT}}/g, meta.choiceCount || 0)
  .replace(/{{SHORT_COUNT}}/g, meta.shortCount || 0)
  .replace(/{{CODE_COUNT}}/g, meta.codeCount || 0)
  .replace(/{{TOTAL_COUNT}}/g, meta.total || 0);

// Generate app.js from data
const appJS = generateAppJS(examData);

// Validate JS
function validateJS(label, code) {
  try { new Function(code); return true; }
  catch(e) { console.error(`[FAIL] ${label}: ${e.message}`); return false; }
}

if (!validateJS('app', appJS)) process.exit(1);
if (!validateJS('skulpt', skulptJS)) process.exit(1);
console.log('[OK] All JS validated');

// Assemble HTML
const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escHtml(title)}</title>
<style>${cmCSSText}</style>
<style>${styles}</style>
</head>
<body>
${body}
<script>${cmJS}</script>
<script>${confettiJS}</script>
<script>${skulptJS}</script>
<script>${skulptStdlibJS}</script>
<script>${appJS}</script>
</body>
</html>`;

// Output
let outPath;
if (outputIdx >= 0 && args[outputIdx + 1]) {
  outPath = args[outputIdx + 1];
} else {
  outPath = path.join(path.dirname(dataPath), title + '.html');
}

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, html, 'utf8');
const sizeMB = (Buffer.byteLength(html) / 1024 / 1024).toFixed(2);
console.log(`\nBuild complete: ${sizeMB}MB`);
console.log(`Output: ${outPath}`);

// ===== APP.JS GENERATOR =====
function generateAppJS(data) {
  const chJSON = JSON.stringify(data.CH, null, 0);
  const shJSON = JSON.stringify(data.SH, null, 0);
  const cdJSON = JSON.stringify(data.CD, null, 0);

  return `'use strict';

/* ===== DATA — Auto-generated by montest ===== */
var CH = ${chJSON};
var SH = ${shJSON};
var CD = ${cdJSON};

/* ===== STATE ===== */
var CE = {}, editors = {}, done = {};

function init() {
  try { CE = JSON.parse(localStorage.getItem('montest_state') || '{}'); } catch(e) { CE = {}; }
  switchTab('choice');
  updateProgress();
}

function save() {
  try { localStorage.setItem('montest_state', JSON.stringify(CE)); } catch(e) {}
}

function toggleTheme() {
  var h = document.documentElement;
  var next = h.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
  h.setAttribute('data-theme', next);
  try { localStorage.setItem('montest_theme', next); } catch(e) {}
}

(function() {
  try {
    var t = localStorage.getItem('montest_theme');
    if (t) document.documentElement.setAttribute('data-theme', t);
  } catch(e) {}
})();

/* ===== TABS ===== */
function switchTab(tab) {
  document.querySelectorAll('.tab').forEach(function(t) { t.classList.remove('on'); });
  var tabs = document.querySelectorAll('.tab');
  var idx = tab === 'choice' ? 0 : tab === 'short' ? 1 : 2;
  if (tabs[idx]) tabs[idx].classList.add('on');
  render(tab);
}

/* ===== RENDER ===== */
function render(tab) {
  var app = document.getElementById('app');
  if (!app) return;
  if (tab === 'choice') renderChoice(app);
  else if (tab === 'short') renderShort(app);
  else renderCode(app);
}

function renderChoice(app) {
  var html = '';
  for (var i = 0; i < CH.length; i++) {
    var q = CH[i];
    var sel = CE['ch_' + q.id];
    var checked = sel !== undefined;
    var correct = checked && sel === q.a;
    var wrong = checked && sel !== q.a;
    var cls = 'qc' + (correct ? ' ok' : '') + (wrong ? ' no' : '');
    html += '<div class="' + cls + '" style="animation-delay:' + (i * 0.03) + 's">';
    html += '<div class="qn">选择题 ' + q.id + '</div>';
    html += '<div class="qt">' + q.q + '</div>';
    for (var j = 0; j < q.o.length; j++) {
      var ocls = 'ob';
      if (sel === j) ocls += ' sel';
      if (checked && j === q.a) ocls += ' correct';
      if (sel === j && sel !== q.a) ocls += ' wrong';
      html += '<div class="' + ocls + '" onclick="pickChoice(' + q.id + ',' + j + ')">';
      html += '<span class="ol">' + 'ABCD'[j] + '</span>';
      html += '<span class="ot">' + q.o[j] + '</span>';
      html += '</div>';
    }
    if (checked) {
      html += '<div class="exp' + (correct ? ' exp-ok' : ' exp-no') + '">';
      html += (correct ? '&#10003; ' : '&#10007; ') + (q.e || '请查看解析');
      html += '</div>';
    }
    html += '</div>';
  }
  app.innerHTML = html;
}

function pickChoice(id, idx) {
  if (CE['ch_' + id] !== undefined) return;
  CE['ch_' + id] = idx;
  save();
  render('choice');
  updateProgress();
}

function renderShort(app) {
  var html = '';
  for (var i = 0; i < SH.length; i++) {
    var q = SH[i];
    var show = CE['sh_' + q.id];
    html += '<div class="qc" style="animation-delay:' + (i * 0.03) + 's">';
    html += '<div class="qn">简答题 ' + q.id + '</div>';
    html += '<div class="qt">' + q.q + '</div>';
    html += '<div class="sa-btn">';
    html += '<button class="btn bo" onclick="toggleShort(' + q.id + ')">';
    html += show ? '&#9650; 收起参考答案' : '&#9660; 查看参考答案';
    html += '</button></div>';
    if (show) {
      html += '<div class="sa-ans">' + (q.a || '<em>暂无答案</em>') + '</div>';
      CE['sh_' + q.id] = 1;
    }
    html += '</div>';
  }
  app.innerHTML = html;
  save();
}

function toggleShort(id) {
  if (CE['sh_' + id]) delete CE['sh_' + id];
  else CE['sh_' + id] = 1;
  save();
  render('short');
  updateProgress();
}

function renderCode(app) {
  var html = '';
  for (var i = 0; i < CD.length; i++) {
    var q = CD[i];
    html += '<div class="qc" style="animation-delay:' + (i * 0.03) + 's">';
    html += '<div class="qn">编程题 ' + q.id + '</div>';
    html += '<div class="qt">' + q.q + '</div>';
    html += '<div class="ed-wrap"><div id="ed-' + q.id + '" class="ed"></div></div>';
    html += '<div class="code-btns">';
    html += '<button class="btn bp" onclick="runTests(' + q.id + ')">&#9654; 运行测试</button>';
    html += '<button class="btn bo" onclick="toggleCodeAns(' + q.id + ')">&#128203; 参考答案</button>';
    html += '<button class="btn bo" onclick="resetCode(' + q.id + ')">&#8634; 重置</button>';
    html += '</div>';
    html += '<div id="tr-' + q.id + '" class="tr"></div>';
    if (CE['ca_' + q.id]) {
      html += '<div class="sa-ans"><pre><code>' + escH((q.a || '').replace(/\\\\n/g, '\\n')) + '</code></pre></div>';
    }
    html += '<div id="toast-' + q.id + '" class="toast"></div>';
    html += '</div>';
  }
  app.innerHTML = html;
  initEditors();
  save();
}

function toggleCodeAns(id) {
  if (CE['ca_' + id]) delete CE['ca_' + id];
  else CE['ca_' + id] = 1;
  save();
  render('code');
}

function resetCode(id) {
  delete CE['cv_' + id];
  if (editors[id]) { editors[id].setValue(CD.find(function(c){return c.id===id;}).s || ''); }
}

function escH(s) { return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

/* ===== CODEMIRROR ===== */
var PY_KW = ['False','None','True','and','as','assert','async','await','break','class','continue','def','del','elif','else','except','finally','for','from','global','if','import','in','is','lambda','nonlocal','not','or','pass','raise','return','try','while','with','yield','print','range','len','int','str','float','list','dict','set','tuple','type','input','open','enumerate','zip','map','filter','sorted','reversed','abs','max','min','sum','isinstance','hasattr','getattr','setattr','any','all','bin','hex','oct','chr','ord','pow','round','callable','dir','eval','exec','format','hash','id','locals','globals','vars','super','property','classmethod','staticmethod','append','extend','insert','remove','pop','clear','index','count','sort','reverse','copy','keys','values','items','get','update','setdefault','upper','lower','strip','split','join','replace','find','count','startswith','endswith','encode','decode','time','math','random','datetime','collections','functools','itertools','re','json','os','sys','threading','ValueError','TypeError','KeyError','IndexError','FileNotFoundError','RuntimeError'];

function initEditors() {
  if (typeof CodeMirror === 'undefined') return;
  CD.forEach(function(c) {
    var el = document.getElementById('ed-' + c.id);
    if (!el) return;
    var saved = CE['cv_' + c.id];
    editors[c.id] = CodeMirror(el, {
      value: saved || c.s || '# Write your code here\\n',
      mode: 'python',
      theme: document.documentElement.getAttribute('data-theme') === 'dark' ? 'material-darker' : 'default',
      lineNumbers: true,
      indentUnit: 4,
      tabSize: 4,
      indentWithTabs: false,
      autoCloseBrackets: true,
      matchBrackets: true,
      extraKeys: {
        'Ctrl-Space': 'autocomplete',
        'Tab': function(cm) {
          if (cm.somethingSelected()) cm.indentSelection('add');
          else cm.replaceSelection('    ', 'end');
        }
      },
      hintOptions: { completeSingle: false }
    });
    editors[c.id].on('change', function() {
      CE['cv_' + c.id] = editors[c.id].getValue();
      save();
    });
  });
}

/* ===== SKULPT PYTHON RUNNER ===== */
function skRun(code) {
  return new Promise(function(resolve, reject) {
    var output = [];
    Sk.configure({
      output: function(text) { output.push(text); },
      read: function(x) {
        if (Sk.builtinFiles && Sk.builtinFiles["files"][x]) return Sk.builtinFiles["files"][x];
        throw "File not found: '" + x + "'";
      }
    });
    Sk.misceval.asyncToPromise(function() {
      return Sk.importMainWithBody('<stdin>', false, code, true);
    }).then(function(mod) {
      resolve({ mod: mod, output: output });
    }, function(err) {
      reject(err);
    });
  });
}

function skToJS(v) {
  if (v === Sk.builtin.none.none$) return null;
  if (v instanceof Sk.builtin.str) return v.v;
  if (v instanceof Sk.builtin.int_ || v instanceof Sk.builtin.float_) return Number(v);
  if (v instanceof Sk.builtin.bool) return v.v ? true : false;
  if (v instanceof Sk.builtin.list) return v.ob_array.map(skToJS);
  if (v instanceof Sk.builtin.tuple) return v.ob_array.map(skToJS);
  if (v instanceof Sk.builtin.dict) {
    var items = v.tp$as_sequence ? v.tp$as_sequence() : [];
    var obj = {};
    items.forEach(function(kv) { obj[skToJS(kv[0])] = skToJS(kv[1]); });
    return obj;
  }
  return v;
}

async function runTests(id) {
  var c = CD.find(function(x){return x.id===id;});
  if (!c || !c.t || !c.t.length) {
    showToast(id, '该题暂无测试用例', 'warn');
    return;
  }
  var code = editors[id].getValue();
  var box = document.getElementById('tr-' + id);
  box.innerHTML = '<div class="tr-loading">&#8987; Running...</div>';

  var passed = 0, total = c.t.length, html = '<div class="test-panel">';
  for (var i = 0; i < c.t.length; i++) {
    var tc = c.t[i];
    try {
      var fullCode = code + '\\n' + tc.c;
      var result = await skRun(fullCode);
      var actual = result.output.length > 0 ? result.output[result.output.length - 1].trim() : '';
      var expected = String(tc.e);
      var pass = actual === expected;
      if (pass) passed++;
      html += '<div class="tc ' + (pass ? 'tc-pass' : 'tc-fail') + '">';
      html += '<span class="tc-icon">' + (pass ? '&#10003;' : '&#10007;') + '</span>';
      html += '<span class="tc-detail"><code>print(' + escH(tc.c) + ')</code></span>';
      html += '<span class="tc-expected">期望: <code>' + escH(expected) + '</code></span>';
      if (!pass) html += '<span class="tc-actual">实际: <code>' + escH(actual) + '</code></span>';
      html += '</div>';
    } catch(err) {
      html += '<div class="tc tc-fail">';
      html += '<span class="tc-icon">&#10007;</span>';
      html += '<span class="tc-detail"><code>' + escH(tc.c) + '</code></span>';
      html += '<span class="tc-err">' + escH(String(err)) + '</span>';
      html += '</div>';
    }
  }
  html += '<div class="tr-sum' + (passed === total ? ' tr-ok' : '') + '">';
  html += passed + ' / ' + total + ' 测试用例通过';
  html += '</div></div>';
  box.innerHTML = html;

  if (passed === total) celebrate();
}

function showToast(id, msg, type) {
  var t = document.getElementById('toast-' + id);
  if (!t) return;
  t.textContent = msg;
  t.className = 'toast toast-' + (type || 'info') + ' toast-show';
  setTimeout(function() { t.className = 'toast'; }, 3000);
}

/* ===== PROGRESS ===== */
function updateProgress() {
  var total = CH.length + SH.length;
  var completed = 0;
  CH.forEach(function(q) { if (CE['ch_' + q.id] !== undefined) completed++; });
  SH.forEach(function(q) { if (CE['sh_' + q.id]) completed++; });
  var pct = total > 0 ? Math.round(completed / total * 100) : 0;
  var fill = document.getElementById('pFill');
  var txt = document.getElementById('pTxt');
  if (fill) fill.style.width = pct + '%';
  if (txt) txt.textContent = completed + ' / ' + total + ' 已完成';
}

function resetAll() {
  if (!confirm('确定要重置所有进度吗？')) return;
  CE = {};
  save();
  switchTab('choice');
}

/* ===== CELEBRATION ===== */
function celebrate() {
  if (typeof confetti !== 'function') return;
  var effects = [
    function() { confetti({particleCount:100,spread:70,origin:{x:0.1,y:0.6}}); confetti({particleCount:100,spread:70,origin:{x:0.9,y:0.6}}); },
    function() { var c=['#ff0000','#00ff00','#0000ff','#ffff00','#ff00ff']; for(var i=0;i<5;i++) setTimeout(function(){confetti({particleCount:30,spread:360,startVelocity:30,origin:{x:Math.random(),y:Math.random()*0.5},colors:c});},i*300); },
    function() { confetti({particleCount:80,spread:100,origin:{y:0},shapes:['star'],colors:['#ffd700','#ffec8b','#daa520'],gravity:0.5,scalar:1.2}); },
    function() { confetti({particleCount:60,spread:120,origin:{y:0,x:0.5},gravity:0.3,scalar:1.5,shapes:['circle'],colors:['#fce4ec','#f8bbd0','#f48fb1','#f06292','#ec407a']}); }
  ];
  var idx = Math.floor(Math.random() * effects.length);
  effects[idx]();
}

init();
`;
}

function escHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
